[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }

[profile.release]
strip = "symbols"
lto = "yes"
opt-level = "z"
codegen-units = 1
#panic = abort
